version: "3.8" 
services:
  node:
    container_name: "node"
    build: .
    volumes:
      - ./:/home/node/app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - postgres  
    command: "npm start"
  db:
    container_name: "postgis"
    image: "postgis/postgis"
    ports: 
      - "5433:5432"
    volumes:
       - pgdata:/var/lib/postgrespers
    env_file:
      - .env-postgres
    networks:
      - postgres
networks:
  postgres:
volumes:
  pgdata : {}